### ISSUE TITLE
qr-data-reconstruct for raspberry pi

### ISSUE THREAD

**Issue by johnshearing** [Prodicode/qr-data-reconstruct#1]
Hi, it seems that:
 `sudo pip install opencv-python`
and 
`sudo pip install zbar`
do not work on the raspberry pi.

Is there a work around for this?
Perhaps a different package manager or perhaps is there a way to compile these myself.
Sorry for the Noob question. I am a bit new to Linux
Thanks John

**Comment by johnshearing** [comment]
This one seems to have cleared my zbar dependencey error:
sudo apt-get install python-zbar

This video [Raspberry Pi 2 and OpenCV 3 Tutorial Part 1](https://www.youtube.com/watch?v=6j-Wy9j0TCs)
Which is meant to be used with [this cheatsheet](https://github.com/MicrocontrollersAndMore/Raspberry_Pi_2_and_OpenCV_3_Tutorial_Part_1/blob/master/Raspberry%20Pi%202%20%2B%20OpenCV%203%20Cheat%20Sheet.txt)
Allowed me to install OpenCV on my raspberry pi.

Everything worked great!

My application is secure encrypted messaging between airgapped devices.
https://www.youtube.com/channel/UCQlQRc9muSqPZIXSfugN43A

Thank you Tudor Gheorghiu for making this possible.

**Comment by RedaOps** [comment]
I am really sorry for not responding to this issue, for some reason I had some problems with notifications. Glad you solved the issue!

Tudor
